<div class="row">
  <div class="col-md-6">
    <div class="row footer-links">
      <div class="col-sm-4">
        <?php echo $this->getFooterMenu('footer-json-1'); ?>
      </div>
      <div class="col-sm-4">
        <?php echo $this->getFooterMenu('footer-json-2'); ?>
      </div>
      <div class="col-sm-4">
        <?php echo $this->getFooterMenu('footer-json-3'); ?>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="row">
        <div class="col-sm-6 social-links">
            <ul class="nav navbar-nav">
                <li><a href="#"><img src="<?php echo $this->getViewFileUrl('Scriptkid_Typo3menu::images/social-tripadvisor.png'); ?>" alt="Tripadvisor"></a></li>
                <li><a href="#"><img src="<?php echo $this->getViewFileUrl('Scriptkid_Typo3menu::images/social-facebook.png'); ?>" alt="Facebook"></a></li>
                <li><a href="#"><img src="<?php echo $this->getViewFileUrl('Scriptkid_Typo3menu::images/social-twitter.png'); ?>" alt="Twitter"></a></li>
            </ul>
        </div>
        <div class="col-sm-6 footer-links">
            <ul class="nav navbar-nav pull-right">
                <li><a href="/customer/account/">Login</a></li>
            </ul>
        </div>
    </div>
  </div>
</div>
